import boto3

# === Configuration ===
bucket_name = 'automuse-output'
region = 'ap-south-1'
prefix = 'generated_tracks/'

# === Get all files from S3 ===
s3 = boto3.client('s3', region_name=region)
response = s3.list_objects_v2(Bucket=bucket_name, Prefix=prefix)

audio_files = [obj['Key'] for obj in response.get('Contents', []) if obj['Key'].endswith('.wav')]

# === Start HTML content ===
html = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Automuse - AI Generated Music</title>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 text-gray-800 font-sans">

  <header class="bg-black text-white py-6 shadow-lg">
    <div class="container mx-auto px-4">
      <h1 class="text-3xl font-bold">🎵 AI Generated Rock Tracks</h1>
      <p class="text-sm mt-2">All tracks are generated by AI and hosted via AWS S3</p>
    </div>
  </header>

  <main class="container mx-auto px-4 py-10">
    <div id="music-list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
'''

# === Add each audio player ===
for file in sorted(audio_files, reverse=True):
    filename = file.split('/')[-1].replace('.wav', '')
    audio_url = f"https://{bucket_name}.s3.{region}.amazonaws.com/{file}"
    html += f'''
      <div class="bg-white p-4 rounded-xl shadow-md">
        <h2 class="text-lg font-semibold mb-2">{filename}</h2>
        <audio controls class="w-full">
          <source src="{audio_url}" type="audio/wav">
          Your browser does not support the audio element.
        </audio>
      </div>
    '''

# === End HTML ===
html += '''
    </div>
  </main>
</body>
</html>
'''

# === Save locally ===
with open('index.html', 'w') as f:
    f.write(html)

print("✅ index.html generated.")

# === Upload back to S3 ===
s3.upload_file('index.html', bucket_name, 'index.html', ExtraArgs={'ACL': 'public-read'})
print("☁ index.html uploaded to S3.")
print(f"🔗 View site: http://{bucket_name}.s3-website.{region}.amazonaws.com/")
